terminal = "kitty"
editor = "vim"
editor_cmd = terminal .. " -e " .. editor
music_player = terminal .. " -e cmus"
file_manager = "pcmanfm"
browser = "google-chrome-stable"
telegram = "telegram-desktop"
make_screenshot = "gnome-screenshot"
screenshot_path = "/home/sheh/Pictures/Screenshots"
